{% set name = "brainreg" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainreg-{{ version }}.tar.gz
  sha256: f7d7228b52016407c5973a2d21fa3f4a74b19c4e7c57d21c5d03631a1c2b1aae

build:
  entry_points:
    - brainreg = brainreg.core.cli:main
  noarch: python
  script:
    # Remove niftyreg binaries in the PyPI distribution as we should depend on
    # niftyreg as already packaged in conda-forge
    - rm -r brainreg/core/bin  # [not win]
    - rd /s /q "brainreg/core/bin"  # [win]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - brainglobe-atlasapi
    - brainglobe-space
    - brainglobe-napari-io
    - brainglobe-segmentation >=1.0.0
    - brainglobe-utils >=0.2.7
    - fancylog
    - magicgui
    - napari-plugin-engine >=0.1.4
    - napari
    - pyqt
    - pandas
    - scipy
    - tqdm
    - numpy
    - pooch >1
    - qtpy
    - scikit-image

test:
  imports:
    - brainreg
  commands:
    - pip check
    - brainreg --help
  requires:
    - pip

about:
  summary: Automated 3D brain registration
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://docs.brainglobe.info/brainreg/introduction

extra:
  recipe-maintainers:
    - adamltyson
