{% set name = "brainreg" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainreg-{{ version }}.tar.gz
  sha256: 703457275974c4de63e1c9a1836c1b59856334f85fd95b3c2b3767f12a0085f8

build:
  entry_points:
    - brainreg = brainreg.cli:main
  noarch: python
  script:
    # Remove niftyreg binaries in the PyPI distribution as we should depend on
    # niftyreg as already packaged in conda-forge
    - rm -r src/brainreg/bin  # [not win]
    - rd /s /q "src/brainreg/bin"  # [win]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bg-atlasapi
    - bg-space
    - niftyreg
    - numpy
    - configparser
    - scikit-image
    - imio
    - fancylog
    - brainglobe-utils
    - scipy
    - pandas
    - tqdm

test:
  imports:
    - brainreg
  commands:
    - pip check
    - brainreg --help
  requires:
    - pip

about:
  summary: Automated 3D brain registration
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://docs.brainglobe.info/brainreg/introduction

extra:
  recipe-maintainers:
    - adamltyson
